from __future__ import annotations


SHEET_SCHEMAS: dict[str, list[str]] = {
    "Users": [
        "user_id", "email", "display_name", "created_utc", "updated_utc",
        "theme_name", "large_text", "reduce_motion", "walkthrough_complete",
    ],
    "Locations": [
        "location_id",
        "user_id",
        "label",
        "city",
        "region",
        "country",
        "grid",
        "latitude",
        "longitude",
        "is_home",
        "created_utc",
    ],
    "Logging Entries": [
        "log_id",
        "user_id",
        "location_id",
        "station_id",
        "band",
        "frequency",
        "call",
        "station_city",
        "station_region",
        "station_country",
        "station_county",
        "station_grid",
        "station_latitude",
        "station_longitude",
        "reception_utc",
        "distance_miles",
        "propagation",
        "is_sdr",
        "is_portable",
        "notes",
        "source",
        "import_batch_id",
        "created_utc",
        "updated_utc",
        "deleted_utc",
        "revision",
    ],
    "Bandscan": [
        "bandscan_id",
        "user_id",
        "location_id",
        "band",
        "frequency",
        "status",
        "station_id",
        "call",
        "reviewed_utc",
    ],
    "Import Batches": [
        "batch_id",
        "user_id",
        "filename",
        "source_format",
        "date_protocol",
        "time_protocol",
        "timezone",
        "row_count",
        "accepted_count",
        "status",
        "created_utc",
    ],
    "Import Review": [
        "review_id",
        "batch_id",
        "source_row",
        "status",
        "original_json",
        "normalized_json",
        "message",
    ],
    "Announcements": ["announcement_id", "title", "body", "published_utc", "active"],
    "Support Tickets": ["ticket_id", "user_id", "category", "subject", "details", "created_utc", "status"],
}
