from __future__ import annotations


SHEET_SCHEMAS: dict[str, list[str]] = {
    "Users": [
        "user_id", "email", "display_name", "created_utc", "updated_utc",
        "theme_name", "large_text", "reduce_motion", "walkthrough_complete",
    ],
    "Locations": [
        "location_id",
        "user_id",
        "label",
        "city",
        "region",
        "country",
        "grid",
        "latitude",
        "longitude",
        "is_home",
        "created_utc",
    ],
    "Logging Entries": [
        "log_id",
        "user_id",
        "location_id",
        "station_id",
        "band",
        "frequency",
        "call",
        "station_city",
        "station_region",
        "station_country",
        "station_county",
        "station_grid",
        "station_latitude",
        "station_longitude",
        "reception_utc",
        "distance_miles",
        "propagation",
        "is_sdr",
        "is_portable",
        "notes",
        "source",
        "station_review_status",
        "import_batch_id",
        "created_utc",
        "updated_utc",
        "deleted_utc",
        "revision",
    ],
    "Bandscan": [
        "bandscan_id",
        "user_id",
        "location_id",
        "band",
        "frequency",
        "status",
        "station_id",
        "call",
        "reviewed_utc",
    ],
    "Import Batches": [
        "batch_id",
        "user_id",
        "filename",
        "source_format",
        "date_protocol",
        "time_protocol",
        "timezone",
        "row_count",
        "accepted_count",
        "status",
        "created_utc",
    ],
    "Import Review": [
        "review_id",
        "batch_id",
        "source_row",
        "status",
        "original_json",
        "normalized_json",
        "message",
    ],
    "Station Overrides": [
        "station_id", "band", "frequency", "call", "city", "region", "country",
        "county", "grid", "latitude", "longitude", "source_log_id",
        "approved_utc", "updated_utc",
    ],
    "Announcements": [
        "announcement_id", "title", "body", "start_utc", "end_utc", "active",
        "published_utc", "updated_utc",
    ],
    "Challenges": [
        "challenge_id", "challenge_type", "challenge_name", "timeframe_tag",
        "start_utc", "end_utc", "bands", "frequencies", "include_countries",
        "exclude_countries", "include_regions", "exclude_regions",
        "propagation_modes", "dayparts", "min_distance", "max_distance",
        "scoring_method", "description", "active", "created_utc", "updated_utc",
    ],
    "Support Tickets": [
        "ticket_id", "user_id", "category", "subject", "details", "created_utc",
        "updated_utc", "status", "admin_comment",
    ],
    "Shoutout Status": [
        "entry_id", "read_on_air", "read_utc", "updated_utc",
    ],
}
